// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe               = require("reason-react/src/ReactDOMRe.js");
var ReasonReact              = require("reason-react/src/ReasonReact.js");
var Page$ReactTemplate       = require("./page.bs.js");
var RootRouter$ReactTemplate = require("./RootRouter.bs.js");

function render(param) {
  var match = param[1][/* path */0];
  if (match) {
    return ReasonReact.element(/* None */0, /* None */0, Page$ReactTemplate.make("Not Found", /* array */[]));
  } else {
    return ReasonReact.element(/* None */0, /* None */0, Page$ReactTemplate.make("Main Page", /* array */[]));
  }
}

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, RootRouter$ReactTemplate.make(render)), "index");

exports.render = render;
/*  Not a pure module */
