// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function emptyLoc() {
  return /* record */[
          /* path : [] */0,
          /* hash */"",
          /* search */""
        ];
}

var component = ReasonReact.reducerComponent("Router");

function make(_children) {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function () {
      var match = typeof (window) === "undefined" ? undefined : (window);
      if (match !== undefined) {
        var appLoad = new Event("popstate");
        +match.dispatchEvent(appLoad);
        return /* NoUpdate */0;
      } else {
        return /* NoUpdate */0;
      }
    });
  newrecord[/* render */9] = (function (self) {
      return Curry._1(_children, /* tuple */[
                  self[/* state */2][/* prevLocation */0],
                  self[/* state */2][/* nextLocation */1]
                ]);
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* prevLocation : record */[
                /* path : [] */0,
                /* hash */"",
                /* search */""
              ],
              /* nextLocation : record */[
                /* path : [] */0,
                /* hash */"",
                /* search */""
              ]
            ];
    });
  newrecord[/* reducer */12] = (function (msg, state) {
      return /* Update */Block.__(0, [/* record */[
                  /* prevLocation */state[/* nextLocation */1],
                  /* nextLocation */msg[0]
                ]]);
    });
  newrecord[/* subscriptions */13] = (function (param) {
      var send = param[/* send */4];
      return /* :: */[
              /* Sub */[
                (function () {
                    return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                  return Curry._1(send, /* Route */[url]);
                                }));
                  }),
                ReasonReact.Router[/* unwatchUrl */2]
              ],
              /* [] */0
            ];
    });
  return newrecord;
}

exports.emptyLoc  = emptyLoc;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
